# \uD3EC\uD2B8 \uBC0F \uC778\uC99D\uC11C \uC124\uC815
server.port=8081
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl/intranet.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=rkskekfk12
server.ssl.key-alias=intranet
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# \uB4DC\uB77C\uC774\uBC84
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# MSSQL
spring.datasource.url=jdbc:log4jdbc:${DB_URL};sendStringParametersAsUnicode=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

security.decrypt.key=ENC(hdA6ViVPtQf09dTBYvDPqV6zN3l0CcF2x+EMVV8kpi6hxwqQixK1LBQ4BrGNa0Iw)

# HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.leak-detection-threshold=20000

# MyBatis
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.use-actual-param-name=true

# JSP Engine
server.servlet.jsp.init-parameters.development=true

# Spring
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

# \uC138\uC158, \uB85C\uADF8\uC778 \uD0C0\uC784\uC544\uC6C3 \uC2DC\uAC04
server.servlet.session.timeout=60m
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict

# \uB85C\uADF8\uC778 \uC0C1\uD0DC \uC720\uC9C0 \uD0A4
security.remember-me.key=${JASYPT_ENCRYPTOR_PASSWORD}

logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG

# \uAC1C\uBC1C 130\uBCF8\uC11C\uBC84 132\uBC31\uC5C5\uC11C\uBC84
file.nas.base-dir=\\\\192.168.100.132\\PointFtp\\Intranet

# \uC6B4\uC601, \uC774\uAC70 \uD0A4\uACE0 logback-spring \uAC00\uC11C \uB85C\uADF8 \uB2E4 \uB044\uAE30
#file.nas.base-dir=/PointFtp/Intranet

# \uC5D0\uB7EC \uD398\uC774\uC9C0
server.error.whitelabel.enabled=false
server.error.path=/error
server.error.include-stacktrace=never
server.error.include-message=never
